### ISSUE TITLE
GIF as a background

### ISSUE THREAD

**Issue by josephshambrook** [hasitcomehome/hasitcomehome.github.io#4]
(Couldn't push my new branch as I don't have the right to).

That background is pretty bog standard. I'd say let's update it with a [GIF](https://media.giphy.com/media/QPoeHFEWmblsMfrE3k/giphy.gif) that would make St George himself weep silent tears.

One line change too. Update `background-image: url(../bg.jpg);` to be `background-image: url('https://media.giphy.com/media/QPoeHFEWmblsMfrE3k/giphy.gif');`

**Comment by bouge** [comment]
Thanks @josephshambrook for the suggestion. Feel free to raise a PR, although because the background doesn't loop, we may need @cdralderson to do some usability testing.
